model:
  prompt_template: "a photo of x x"
  clip_model: "ViT-L/14"
  width_img: 1024
  width_txt: 768


train:
  dataset: aoclevr
  dataset_path: "../../../dataset/aoclevr"
  lr: 0.00005
  dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 128
  gradient_accumulation_steps: 2
  seed: 0
  epochs: 30
  epoch_start: 0
  epoch_round: 3
  ent_weight: False
  update: False
  save_path: data/model/aoclevr/drpt
  best_model_metric: best_loss     #best_unseen  best_seen AUC best_loss best_hm
  save_model: True
  load_model: False     # False or model path
  log_id: "This is the training process of drpt"


test:
  eval_batch_size: 256
  load_model: "./data/model/uaoclevr/drpt/best.pt"
  topk: 1
  text_encoder_batch_size: 36